apiVersion: v1
kind: Service
metadata:
  name: {{ template "ghost.fullname" . }}
  labels:
    app: "{{ template "ghost.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: "2368"
    port: 2368
    targetPort: 2368
  selector:
    app: "{{ template "ghost.fullname" . }}"
    release: "{{ .Release.Name }}"