apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: "{{ template "postgresql.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.db.password }}
  postgresql-password: {{ .Values.db.password | b64enc | quote }}
  {{- end }}